sudo: required
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libboost-dev

script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir build
  - cd build
  - cmake ..
  - make
