sudo: required
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libboost1.60-dev

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - mkdir build
  - cd build
  - cmake ..
  - make
