//#ifndef JSS_UNDEFINE_H_INCLUDED
//#define JSS_UNDEFINE_H_INCLUDED

#undef SJSON_CLASS_STRINGIFY_FUNCTION_NAME
#undef SJSON_APPLY_IO_MANIPULATERS
#undef SJSON_WRITE_NAME
#undef SJSON_WRITE_OBJECT_START
#undef SJSON_WRITE_ARRAY_START
#undef SJSON_WRITE_OBJECT_END
#undef SJSON_WRITE_ARRAY_END

//#endif // JSS_UNDEFINE_H_INCLUDED
