//#ifndef JSS_UNDEFINE_H_INCLUDED
//#define JSS_UNDEFINE_H_INCLUDED

#undef CLASS_STRINGIFY_FUNCTION_NAME
#undef APPLY_IO_MANIPULATERS
#undef WRITE_NAME
#undef WRITE_OBJECT_START
#undef WRITE_ARRAY_START
#undef WRITE_OBJECT_END
#undef WRITE_ARRAY_END

//#endif // JSS_UNDEFINE_H_INCLUDED
